#!/usr/bin/env python

import sys, os
sys.path.insert(0,os.getcwd())  
from git import Git

def initial():
  try:
    global app
    from blogtle import app as app
    return True
  except:
    return False

def run_help():
  pass

def init(path=os.getcwd()):
  if path[0] != '.' and path[0] != '/':
    path = os.path.join('./',path)
  if path[-1] != '/':
    path = path + '/'
  
  if not os.path.isdir(path):
    if os.path.isfile(path) or os.path.islink(path):
      print 'The path goes something wrong! Please checkout, or use an other path.'
    else:
      os.mkdir(path)
  
  if len(os.listdir(path)) == 0:
    folder = ['./']
  else:
    folder = []
  
  g = Git(path)
  print "Form github cloning into " + path + ( ' ' if len(folder) else 'PyBlogtle/ ' ) + ". Please wait..."
  g.execute(['git','clone','git@github.com:renn999/PyBlogtle.git']+folder)
  print "Git clone complete. please Try to make configurate in _config.yml and where do you want to host blog"

def setup_deploy():
  i = raw_input('> ')
  g = Git(os.getcwd())
  g.execute(['git', 'remote', 'rename', 'origin', 'pyBlogtle'])
  g.execute(['git', 'branch', '-m', 'master', 'source'])
  g.execute(['git','remote','add','origin',i])
  j = os.path.join(os.getcwd(),'_deploy')
  os.mkdir(j)
  g = Git(j)
  g.init()
  g.execute(['git','remote','add','origin',i])

if __name__ == '__main__':
  if len(sys.argv) > 1:
    if initial():
      if sys.argv[1] == "build":
        print 'Building ...'
        from blogtle import freezer as freezer
        freezer.freeze()
        print 'done!'
      else:
        print 'Running preview, press <ctrl>+<c> to stop.'
        app.run()
    else:
      if sys.argv[1] == "init":
        init(sys.argv[2] if len(sys.argv)>2 else os.getcwd())
      elif sys.argv[1] == "setup_deploy":
        setup_deploy()
      else:
        print 'please run init first. Or there is some thing wrong!'
  else:
    run_help()
